"""Convert briefing markdown to HTML suitable for email clients."""

from __future__ import annotations

import markdown


def markdown_to_html_body(markdown_text: str) -> str:
    """Render briefing markdown to an HTML fragment (headings, tables, links)."""
    return markdown.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "sane_lists", "nl2br"],
        output_format="html5",
    )


def wrap_email_html(body_html: str, *, title: str) -> str:
    """Wrap HTML fragment in a minimal email-safe document with inline CSS."""
    safe_title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{safe_title}</title>
</head>
<body style="margin:0;padding:24px;background:#f6f7f9;color:#1a1a1a;
             font-family:Georgia,'Times New Roman',serif;line-height:1.55;">
  <div style="max-width:720px;margin:0 auto;background:#ffffff;padding:28px 32px;
              border:1px solid #e5e7eb;border-radius:8px;">
    {body_html}
  </div>
  <p style="max-width:720px;margin:16px auto 0;font-size:12px;color:#6b7280;
            font-family:system-ui,sans-serif;">
    Generated by Financial Researcher — not financial advice.
  </p>
</body>
</html>"""


def style_email_tables(html: str) -> str:
    """Add inline styles to tables for common email clients."""
    return (
        html.replace(
            "<table>",
            '<table style="border-collapse:collapse;width:100%;margin:16px 0;'
            'font-size:13px;font-family:system-ui,sans-serif;">',
        )
        .replace(
            "<th>",
            '<th style="border-bottom:2px solid #111827;padding:8px 6px;'
            'text-align:left;font-weight:600;">',
        )
        .replace(
            "<td>",
            '<td style="border-bottom:1px solid #e5e7eb;padding:8px 6px;'
            'vertical-align:top;">',
        )
    )


def briefing_markdown_to_email_html(markdown_text: str, *, title: str) -> str:
    """Full pipeline: markdown → styled HTML email document."""
    body = markdown_to_html_body(markdown_text)
    body = style_email_tables(body)
    return wrap_email_html(body, title=title)
